; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v2.0.4 on Sun Oct 06 2019 14:43:23 GMT-0400 (Eastern Daylight Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


