; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v2.0.4 on Sun Oct 06 2019 14:43:24 GMT-0400 (Eastern Daylight Time)
; Wait for set temperatures to be reached
M116 P0

